# HW2 Problem 3 Job Scheduling

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({"Job":[i for i in range(1,16)],
                  "ProcessingTime":[23,14,7,62,21,17,19,55,16,13,27,31,35,18,9]})

p = df.ProcessingTime.tolist()
p

[23, 14, 7, 62, 21, 17, 19, 55, 16, 13, 27, 31, 35, 18, 9]

In [2]:
import os
import pyomo.environ as pyo
from pyomo.environ import *

from pyomo.opt import SolverFactory

opt = pyo.SolverFactory('glpk')

model = ConcreteModel()

Jobs = p
ProcessingTime = df.values[1,:]
MaxSlots = 100

model.Cmax = Var(within=NonNegativeIntegers, initialize=0)
model.X = Var(range(4), range(len(Jobs)), range(MaxSlots), within=Binary, initialize=0)

model.obj = Objective(expr = model.Cmax, 
                      sense=minimize)
model.constraints = ConstraintList()

# Objective constraint smallest finish time
for i in model.X_index_0.data():
    for j in model.X_index_1.data():
        model.constraints.add(sum([model.X[i,j,t]*(t + p[j]) for t in model.X_index_2.data()]) <= model.Cmax)

# If Xijt selected, the next pj must be 0
#for i in model.X_index_0.data():
#    for j in model.X_index_1.data():
#        for t in model.X_index_2.data():
#            if t+p[j] <= MaxSlots:
#                model.constraints.add(sum([model.X[i,j,s] for s in range(t+1, t+p[j])]) <= (1-model.X[i,j,t]) )
#            else:
#                model.constraints.add(sum([model.X[i,j,s] for s in range(t+1, MaxSlots)]) <= (1-model.X[i,j,t]) )           

# Once a machine starts a job it can't start another job until it is finished
# For every machine (include yourself), if a job is selected then the total number of you/other machines and jobs taken during the next t+1 .. t+pj slots must be 0
for i in model.X_index_0.data():
    for itick in model.X_index_0.data():
        for jtick in model.X_index_1.data():
            for t in model.X_index_2.data():
                if t+p[j] <= MaxSlots:
                    model.constraints.add(sum([model.X[itick,j,s] for s in range(t+1, t+p[j]) for j in model.X_index_1.data()]) <= (1 - model.X[i,jtick,t]) )
                else:
                    model.constraints.add(sum([model.X[itick,j,s] for s in range(t+1, MaxSlots) for j in model.X_index_1.data()]) <= (1 - model.X[i,jtick,t]) )          

# Total jobs being worked by machine at a time
for i in model.X_index_0.data():
    for t in model.X_index_2.data():
        model.constraints.add(sum([model.X[i,j,t] for j in model.X_index_1.data()]) <= 1 )

# Total machines working on a job at a time
for j in model.X_index_1.data():
    for t in model.X_index_2.data():
        model.constraints.add(sum([model.X[i,j,t] for i in model.X_index_0.data()]) <= 1 )
        

# If a job starts it must be finished before MaxSlots
#for i in model.X_index_0.data():
#    for j in model.X_index_1.data():
#        for t in model.X_index_2.data():
#            model.constraints.add(model.X[i,j,t](t + p[j]) <= model.X[i,j,t]*MaxSlots )

# Every job must get done
for j in model.X_index_1.data():
    model.constraints.add(sum([model.X[i,j,t] for i in model.X_index_0.data() for t in model.X_index_2.data()]) >= 1)
#model.constraints.add(sum([model.X[i,j,t] for i in model.X_index_0.data() for t in model.X_index_2.data() for j in model.X_index_1.data()]) >= len(Jobs))



# Solution

In [ ]:
# Create a model instance and optimize
instance = model.create_instance()
results = opt.solve(instance, tee=True)
instance.display()


    model; returning a clone of the current model instance.
GLPSOL: GLPK LP/MIP Solver, v4.65
Parameter(s) specified in the command line:
 --write C:\Users\bmccs\AppData\Local\Temp\tmp7cum0xwe.glpk.raw --wglp C:\Users\bmccs\AppData\Local\Temp\tmp67wrv3yu.glpk.glp
 --cpxlp C:\Users\bmccs\AppData\Local\Temp\tmpxck69jnp.pyomo.lp
Reading problem data from 'C:\Users\bmccs\AppData\Local\Temp\tmpxck69jnp.pyomo.lp'...
C:\Users\bmccs\AppData\Local\Temp\tmpxck69jnp.pyomo.lp:2882402: warning: lower bound of variable 'x2' redefined
C:\Users\bmccs\AppData\Local\Temp\tmpxck69jnp.pyomo.lp:2882402: warning: upper bound of variable 'x2' redefined
25976 rows, 6002 columns, 2798461 non-zeros
6001 integer variables, 6000 of which are binary
2888402 lines were read
Writing problem data to 'C:\Users\bmccs\AppData\Local\Temp\tmp67wrv3yu.glpk.glp'...
2856421 lines were written
GLPK Integer Optimizer, v4.65
25976 rows, 6002 columns, 2798461 non-zeros
6001 integer variables, 6000 of which are binary
Preprocessi

+  4657: mip =     not found yet >=   1.600000000e+01        (88; 0)
+  4678: mip =     not found yet >=   1.600000000e+01        (89; 0)
Time used: 566.9 secs.  Memory used: 323.5 Mb.
+  4693: mip =     not found yet >=   1.600000000e+01        (90; 0)
+  4808: mip =     not found yet >=   1.600000000e+01        (91; 0)
+  4906: mip =     not found yet >=   1.600000000e+01        (92; 0)
+  5007: mip =     not found yet >=   1.600000000e+01        (93; 0)
+  5119: mip =     not found yet >=   1.600000000e+01        (94; 0)
+  5314: mip =     not found yet >=   1.600000000e+01        (95; 0)
+  5452: mip =     not found yet >=   1.600000000e+01        (96; 0)
+  5552: mip =     not found yet >=   1.600000000e+01        (97; 0)
+  5648: mip =     not found yet >=   1.600000000e+01        (98; 0)
Time used: 633.6 secs.  Memory used: 329.4 Mb.
+  5697: mip =     not found yet >=   1.600000000e+01        (99; 0)
+  5782: mip =     not found yet >=   1.600000000e+01        (100; 0)
+  5868:

+ 11752: mip =     not found yet >=   1.600000000e+01        (196; 0)
+ 11815: mip =     not found yet >=   1.600000000e+01        (197; 0)
+ 11896: mip =     not found yet >=   1.600000000e+01        (198; 0)
+ 11916: mip =     not found yet >=   1.600000000e+01        (199; 0)
+ 11998: mip =     not found yet >=   1.600000000e+01        (200; 0)
Time used: 1537.5 secs.  Memory used: 329.6 Mb.
+ 12089: mip =     not found yet >=   1.600000000e+01        (201; 0)
+ 12090: mip =     not found yet >=   1.600000000e+01        (202; 0)
+ 12163: mip =     not found yet >=   1.600000000e+01        (203; 0)
+ 12273: mip =     not found yet >=   1.600000000e+01        (204; 0)
+ 12338: mip =     not found yet >=   1.600000000e+01        (205; 0)
+ 12442: mip =     not found yet >=   1.600000000e+01        (206; 0)
+ 12529: mip =     not found yet >=   1.600000000e+01        (207; 0)
Time used: 1605.4 secs.  Memory used: 329.6 Mb.
+ 12641: mip =     not found yet >=   1.600000000e+01        (20

+ 18800: mip =     not found yet >=   1.600000000e+01        (303; 0)
+ 18831: mip =     not found yet >=   1.600000000e+01        (304; 0)
+ 18915: mip =     not found yet >=   1.600000000e+01        (305; 0)
Time used: 2524.4 secs.  Memory used: 329.8 Mb.
+ 18980: mip =     not found yet >=   1.600000000e+01        (306; 0)
+ 19055: mip =     not found yet >=   1.600000000e+01        (307; 0)
+ 19142: mip =     not found yet >=   1.600000000e+01        (308; 0)
+ 19180: mip =     not found yet >=   1.600000000e+01        (309; 0)
+ 19256: mip =     not found yet >=   1.600000000e+01        (310; 0)
+ 19332: mip =     not found yet >=   1.600000000e+01        (311; 0)
+ 19353: mip =     not found yet >=   1.600000000e+01        (312; 0)
Time used: 2592.8 secs.  Memory used: 329.8 Mb.
+ 19393: mip =     not found yet >=   1.600000000e+01        (313; 0)
+ 19498: mip =     not found yet >=   1.600000000e+01        (314; 0)
+ 19575: mip =     not found yet >=   1.600000000e+01        (31

+ 27554: mip =     not found yet >=   1.600000000e+01        (408; 0)
+ 27723: mip =     not found yet >=   1.600000000e+01        (409; 0)
+ 27877: mip =     not found yet >=   1.600000000e+01        (410; 0)
+ 27878: mip =     not found yet >=   1.600000000e+01        (411; 0)
Time used: 3703.5 secs.  Memory used: 330.1 Mb.
+ 27879: mip =     not found yet >=   1.600000000e+01        (412; 0)
+ 27880: mip =     not found yet >=   1.600000000e+01        (413; 0)
+ 27930: mip =     not found yet >=   1.600000000e+01        (414; 0)
+ 28050: mip =     not found yet >=   1.600000000e+01        (415; 0)
+ 28283: mip =     not found yet >=   1.600000000e+01        (416; 0)
Time used: 3764.0 secs.  Memory used: 330.1 Mb.
+ 28359: mip =     not found yet >=   1.600000000e+01        (417; 0)
+ 28487: mip =     not found yet >=   1.600000000e+01        (418; 0)
+ 28567: mip =     not found yet >=   1.600000000e+01        (419; 0)
+ 28668: mip =     not found yet >=   1.600000000e+01        (42

+ 39807: mip =     not found yet >=   1.600000000e+01        (512; 0)
+ 39945: mip =     not found yet >=   1.600000000e+01        (513; 0)
+ 40164: mip =     not found yet >=   1.600000000e+01        (514; 0)
+ 40356: mip =     not found yet >=   1.600000000e+01        (515; 0)
Time used: 4971.7 secs.  Memory used: 330.4 Mb.
+ 40570: mip =     not found yet >=   1.600000000e+01        (516; 0)
+ 40641: mip =     not found yet >=   1.600000000e+01        (517; 0)
+ 40851: mip =     not found yet >=   1.600000000e+01        (518; 0)
+ 41027: mip =     not found yet >=   1.600000000e+01        (519; 0)
+ 41194: mip =     not found yet >=   1.600000000e+01        (520; 0)
Time used: 5036.4 secs.  Memory used: 330.4 Mb.
+ 41373: mip =     not found yet >=   1.600000000e+01        (521; 0)
+ 41383: mip =     not found yet >=   1.600000000e+01        (522; 0)
+ 41477: mip =     not found yet >=   1.600000000e+01        (523; 0)
+ 41575: mip =     not found yet >=   1.600000000e+01        (52

+ 56837: mip =     not found yet >=   1.600000000e+01        (617; 0)
+ 56897: mip =     not found yet >=   1.600000000e+01        (618; 0)
+ 57038: mip =     not found yet >=   1.600000000e+01        (619; 0)
Time used: 6141.3 secs.  Memory used: 330.8 Mb.
+ 57160: mip =     not found yet >=   1.600000000e+01        (620; 0)
+ 57318: mip =     not found yet >=   1.600000000e+01        (621; 0)
+ 57590: mip =     not found yet >=   1.600000000e+01        (622; 0)
+ 57760: mip =     not found yet >=   1.600000000e+01        (623; 0)
+ 57852: mip =     not found yet >=   1.600000000e+01        (624; 0)
+ 58091: mip =     not found yet >=   1.600000000e+01        (625; 0)
+ 58333: mip =     not found yet >=   1.600000000e+01        (626; 0)
Time used: 6207.3 secs.  Memory used: 330.9 Mb.
+ 58484: mip =     not found yet >=   1.600000000e+01        (627; 0)
+ 58697: mip =     not found yet >=   1.600000000e+01        (628; 0)
+ 58932: mip =     not found yet >=   1.600000000e+01        (62

+ 70913: mip =     not found yet >=   1.600000000e+01        (723; 0)
+ 71098: mip =     not found yet >=   1.600000000e+01        (724; 0)
+ 71346: mip =     not found yet >=   1.600000000e+01        (725; 0)
+ 71497: mip =     not found yet >=   1.600000000e+01        (726; 0)
+ 71609: mip =     not found yet >=   1.600000000e+01        (727; 0)
+ 71729: mip =     not found yet >=   1.600000000e+01        (728; 0)
Time used: 7228.1 secs.  Memory used: 331.2 Mb.
+ 71804: mip =     not found yet >=   1.600000000e+01        (729; 0)
+ 71909: mip =     not found yet >=   1.600000000e+01        (730; 0)
+ 72016: mip =     not found yet >=   1.600000000e+01        (731; 0)
+ 72136: mip =     not found yet >=   1.600000000e+01        (732; 0)
+ 72375: mip =     not found yet >=   1.600000000e+01        (733; 0)
+ 72575: mip =     not found yet >=   1.600000000e+01        (734; 0)
Time used: 7289.2 secs.  Memory used: 331.3 Mb.
+ 72828: mip =     not found yet >=   1.600000000e+01        (73

+ 91766: mip =     not found yet >=   1.600000000e+01        (829; 0)
Time used: 8321.4 secs.  Memory used: 331.7 Mb.
+ 92045: mip =     not found yet >=   1.600000000e+01        (830; 0)
+ 92379: mip =     not found yet >=   1.600000000e+01        (831; 0)
+ 92742: mip =     not found yet >=   1.600000000e+01        (832; 0)
+ 92952: mip =     not found yet >=   1.600000000e+01        (833; 0)
+ 93158: mip =     not found yet >=   1.600000000e+01        (834; 0)
+ 93392: mip =     not found yet >=   1.600000000e+01        (835; 0)
Time used: 8382.8 secs.  Memory used: 331.8 Mb.
+ 93665: mip =     not found yet >=   1.600000000e+01        (836; 0)
+ 93766: mip =     not found yet >=   1.600000000e+01        (837; 0)
+ 93892: mip =     not found yet >=   1.600000000e+01        (838; 0)
+ 93948: mip =     not found yet >=   1.600000000e+01        (839; 0)
+ 94186: mip =     not found yet >=   1.600000000e+01        (840; 0)
+ 94458: mip =     not found yet >=   1.600000000e+01        (84

+107258: mip =     not found yet >=   1.600000000e+01        (934; 0)
+107479: mip =     not found yet >=   1.600000000e+01        (935; 0)
+107621: mip =     not found yet >=   1.600000000e+01        (936; 0)
+107803: mip =     not found yet >=   1.600000000e+01        (937; 0)
+108046: mip =     not found yet >=   1.600000000e+01        (938; 0)
Time used: 9482.9 secs.  Memory used: 332.2 Mb.
+108268: mip =     not found yet >=   1.600000000e+01        (939; 0)
+108574: mip =     not found yet >=   1.600000000e+01        (940; 0)
+108781: mip =     not found yet >=   1.600000000e+01        (941; 0)
+108903: mip =     not found yet >=   1.600000000e+01        (942; 0)
+108907: mip =     not found yet >=   1.600000000e+01        (943; 0)
+108908: mip =     not found yet >=   1.600000000e+01        (944; 0)
Time used: 9549.5 secs.  Memory used: 332.2 Mb.
+108911: mip =     not found yet >=   1.600000000e+01        (945; 0)
+108913: mip =     not found yet >=   1.600000000e+01        (94

+121210: mip =     not found yet >=   1.600000000e+01        (1041; 0)
Time used: 10458.1 secs.  Memory used: 332.5 Mb.
+121301: mip =     not found yet >=   1.600000000e+01        (1042; 0)
+121581: mip =     not found yet >=   1.600000000e+01        (1043; 0)
+121726: mip =     not found yet >=   1.600000000e+01        (1044; 0)
+121888: mip =     not found yet >=   1.600000000e+01        (1045; 0)
+122177: mip =     not found yet >=   1.600000000e+01        (1046; 0)
+122399: mip =     not found yet >=   1.600000000e+01        (1047; 0)
Time used: 10524.3 secs.  Memory used: 332.5 Mb.
+122671: mip =     not found yet >=   1.600000000e+01        (1048; 0)
+122854: mip =     not found yet >=   1.600000000e+01        (1049; 0)
+123103: mip =     not found yet >=   1.600000000e+01        (1050; 0)
+123312: mip =     not found yet >=   1.600000000e+01        (1051; 0)
+123450: mip =     not found yet >=   1.600000000e+01        (1052; 0)
+123768: mip =     not found yet >=   1.600000000e

+142329: mip =     not found yet >=   1.600000000e+01        (1145; 0)
+142536: mip =     not found yet >=   1.600000000e+01        (1146; 0)
Time used: 11541.0 secs.  Memory used: 333.0 Mb.
+142736: mip =     not found yet >=   1.600000000e+01        (1147; 0)
+142913: mip =     not found yet >=   1.600000000e+01        (1148; 0)
+143181: mip =     not found yet >=   1.600000000e+01        (1149; 0)
+143358: mip =     not found yet >=   1.600000000e+01        (1150; 0)
+143433: mip =     not found yet >=   1.600000000e+01        (1151; 0)
+143584: mip =     not found yet >=   1.600000000e+01        (1152; 0)
+143641: mip =     not found yet >=   1.600000000e+01        (1153; 0)
+143874: mip =     not found yet >=   1.600000000e+01        (1154; 0)
Time used: 11603.8 secs.  Memory used: 333.1 Mb.
+143987: mip =     not found yet >=   1.600000000e+01        (1155; 0)
+144334: mip =     not found yet >=   1.600000000e+01        (1156; 0)
+144727: mip =     not found yet >=   1.600000000e

+154054: mip =     not found yet >=   1.600000000e+01        (1251; 0)
+154186: mip =     not found yet >=   1.600000000e+01        (1252; 0)
Time used: 12445.7 secs.  Memory used: 333.4 Mb.
+154275: mip =     not found yet >=   1.600000000e+01        (1253; 0)
+154370: mip =     not found yet >=   1.600000000e+01        (1254; 0)
+154578: mip =     not found yet >=   1.600000000e+01        (1255; 0)
+154867: mip =     not found yet >=   1.600000000e+01        (1256; 0)
+154970: mip =     not found yet >=   1.600000000e+01        (1257; 0)
+155082: mip =     not found yet >=   1.600000000e+01        (1258; 0)
+155251: mip =     not found yet >=   1.600000000e+01        (1259; 0)
Time used: 12512.8 secs.  Memory used: 333.4 Mb.
+155311: mip =     not found yet >=   1.600000000e+01        (1260; 0)
+155393: mip =     not found yet >=   1.600000000e+01        (1261; 0)
+155463: mip =     not found yet >=   1.600000000e+01        (1262; 0)
+155553: mip =     not found yet >=   1.600000000e

+172547: mip =     not found yet >=   1.600000000e+01        (1356; 0)
+172742: mip =     not found yet >=   1.600000000e+01        (1357; 0)
+172953: mip =     not found yet >=   1.600000000e+01        (1358; 0)
+173181: mip =     not found yet >=   1.600000000e+01        (1359; 0)
+173491: mip =     not found yet >=   1.600000000e+01        (1360; 0)
Time used: 13504.6 secs.  Memory used: 333.9 Mb.
+173770: mip =     not found yet >=   1.600000000e+01        (1361; 0)
+173943: mip =     not found yet >=   1.600000000e+01        (1362; 0)
+174121: mip =     not found yet >=   1.600000000e+01        (1363; 0)
+174921: mip =     not found yet >=   1.600000000e+01        (1364; 0)
+175007: mip =     not found yet >=   1.600000000e+01        (1365; 0)
+175404: mip =     not found yet >=   1.600000000e+01        (1366; 0)
Time used: 13567.6 secs.  Memory used: 333.9 Mb.
+175596: mip =     not found yet >=   1.600000000e+01        (1367; 0)
+175815: mip =     not found yet >=   1.600000000e

+194665: mip =     not found yet >=   1.600000000e+01        (1461; 0)
+194961: mip =     not found yet >=   1.600000000e+01        (1462; 0)
Time used: 14530.6 secs.  Memory used: 334.4 Mb.
+195165: mip =     not found yet >=   1.600000000e+01        (1463; 0)
+195474: mip =     not found yet >=   1.600000000e+01        (1464; 0)
+195633: mip =     not found yet >=   1.600000000e+01        (1465; 0)
+195914: mip =     not found yet >=   1.600000000e+01        (1466; 0)
+196204: mip =     not found yet >=   1.600000000e+01        (1467; 0)
+196505: mip =     not found yet >=   1.600000000e+01        (1468; 0)
+196726: mip =     not found yet >=   1.600000000e+01        (1469; 0)
Time used: 14597.1 secs.  Memory used: 334.4 Mb.
+196932: mip =     not found yet >=   1.600000000e+01        (1470; 0)
+197144: mip =     not found yet >=   1.600000000e+01        (1471; 0)
+197267: mip =     not found yet >=   1.600000000e+01        (1472; 0)
+197426: mip =     not found yet >=   1.600000000e

+214278: mip =     not found yet >=   1.600000000e+01        (1566; 0)
+214461: mip =     not found yet >=   1.600000000e+01        (1567; 0)
Time used: 15563.0 secs.  Memory used: 334.9 Mb.
+214739: mip =     not found yet >=   1.600000000e+01        (1568; 0)
+214982: mip =     not found yet >=   1.600000000e+01        (1569; 0)
+215346: mip =     not found yet >=   1.600000000e+01        (1570; 0)
+215517: mip =     not found yet >=   1.600000000e+01        (1571; 0)
+215617: mip =     not found yet >=   1.600000000e+01        (1572; 0)
+215847: mip =     not found yet >=   1.600000000e+01        (1573; 0)
+216086: mip =     not found yet >=   1.600000000e+01        (1574; 0)
Time used: 15629.1 secs.  Memory used: 334.9 Mb.
+216135: mip =     not found yet >=   1.600000000e+01        (1575; 0)
+216137: mip =     not found yet >=   1.600000000e+01        (1576; 0)
+216138: mip =     not found yet >=   1.600000000e+01        (1577; 0)
+216139: mip =     not found yet >=   1.600000000e

+225271: mip =     not found yet >=   1.600000000e+01        (1672; 0)
+225273: mip =     not found yet >=   1.600000000e+01        (1673; 0)
+225275: mip =     not found yet >=   1.600000000e+01        (1674; 0)
Time used: 16483.2 secs.  Memory used: 335.2 Mb.
+225277: mip =     not found yet >=   1.600000000e+01        (1675; 0)
+225279: mip =     not found yet >=   1.600000000e+01        (1676; 0)
+225281: mip =     not found yet >=   1.600000000e+01        (1677; 0)
+225283: mip =     not found yet >=   1.600000000e+01        (1678; 0)
+225285: mip =     not found yet >=   1.600000000e+01        (1679; 0)
+225315: mip =     not found yet >=   1.600000000e+01        (1680; 0)
+225345: mip =     not found yet >=   1.600000000e+01        (1681; 0)
+225347: mip =     not found yet >=   1.600000000e+01        (1682; 0)
Time used: 16549.7 secs.  Memory used: 335.2 Mb.
+225349: mip =     not found yet >=   1.600000000e+01        (1683; 0)
+225351: mip =     not found yet >=   1.600000000e

+233711: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1789; 10)
Time used: 17306.1 secs.  Memory used: 335.7 Mb.
+233745: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1790; 10)
+233880: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1791; 10)
+233897: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1792; 10)
+234007: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1793; 10)
+234078: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1794; 10)
+234183: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1795; 10)
+234285: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1796; 10)
Time used: 17374.8 secs.  Memory used: 335.8 Mb.
+234421: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1797; 10)
+234520: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1798; 10)
+234733: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1799; 10)
+234817: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1800; 10)
+234932: mip =   1.610000000e+02 >=   

+243098: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1892; 10)
+243196: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1893; 10)
Time used: 18386.4 secs.  Memory used: 336.0 Mb.
+243293: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1894; 10)
+243454: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1895; 10)
+243540: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1896; 10)
+243604: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1897; 10)
+243715: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1898; 10)
+243876: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1899; 10)
Time used: 18453.2 secs.  Memory used: 336.0 Mb.
+243989: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1900; 10)
+244066: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1901; 10)
+244153: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1902; 10)
+244217: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1903; 10)
+244289: mip =   1.610000000e+02 >=   

+256163: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1995; 10)
+256280: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1996; 10)
+256412: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1997; 10)
+256574: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1998; 10)
+256651: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (1999; 10)
+256751: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2000; 10)
+256869: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2001; 10)
Time used: 19507.2 secs.  Memory used: 336.4 Mb.
+256953: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2002; 10)
+257179: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2003; 10)
+257328: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2004; 10)
+257425: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2005; 10)
+257441: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2006; 10)
+257513: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2007; 10)
+257660: mip = 

+269114: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2098; 10)
+269255: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2099; 10)
+269469: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2100; 10)
Time used: 20644.6 secs.  Memory used: 336.8 Mb.
+269653: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2101; 10)
+269865: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2102; 10)
+270015: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2103; 10)
+270164: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2104; 10)
+270341: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2105; 10)
Time used: 20706.3 secs.  Memory used: 336.8 Mb.
+270504: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2106; 10)
+270603: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2107; 10)
+270604: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2108; 10)
+270605: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2109; 10)
+270609: mip =   1.610000000e+02 >=   

+288903: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2199; 10)
+289117: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2200; 10)
+289260: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2201; 10)
Time used: 21898.5 secs.  Memory used: 337.3 Mb.
+289419: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2202; 10)
+289514: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2203; 10)
+289581: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2204; 10)
+289636: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2205; 10)
+289820: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2206; 10)
+289919: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2207; 10)
Time used: 21967.7 secs.  Memory used: 337.3 Mb.
+290075: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2208; 10)
+290328: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2209; 10)
+290568: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2210; 10)
+290713: mip =   1.610000000e+02 >=   

+312356: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2300; 10)
Time used: 23169.5 secs.  Memory used: 349.7 Mb.
+312672: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2301; 10)
+312959: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2302; 10)
+313195: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2303; 10)
+313428: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2304; 10)
+313618: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2305; 10)
Time used: 23238.4 secs.  Memory used: 349.7 Mb.
+313924: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2306; 10)
+314182: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2307; 10)
+314508: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2308; 10)
+314756: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2309; 10)
+314924: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2310; 10)
Time used: 23308.6 secs.  Memory used: 349.7 Mb.
+315161: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% 

+328174: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2401; 10)
Time used: 24411.6 secs.  Memory used: 350.1 Mb.
+328368: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2402; 10)
+328538: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2403; 10)
+328753: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2404; 10)
+328915: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2405; 10)
+329173: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2406; 10)
Time used: 24473.1 secs.  Memory used: 350.1 Mb.
+329362: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2407; 10)
+329509: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2408; 10)
+329735: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2409; 10)
+329808: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2410; 10)
+329992: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2411; 10)
Time used: 24534.5 secs.  Memory used: 350.2 Mb.
+330152: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% 

+351626: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2502; 10)
+351814: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2503; 10)
+352018: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2504; 10)
+352081: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2505; 10)
Time used: 25680.1 secs.  Memory used: 350.8 Mb.
+352486: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2506; 10)
+352731: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2507; 10)
+352969: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2508; 10)
+353203: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2509; 10)
+353336: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2510; 10)
+353631: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2511; 10)
+353817: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2512; 10)
+354060: mip =   1.610000000e+02 >=   1.600000000e+01  90.1% (2513; 10)
Time used: 25741.9 secs.  Memory used: 350.9 Mb.
+354271: mip =   1.610000000e+02 >=   

+361269: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2607; 22)
+361270: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2608; 22)
+361271: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2609; 22)
+361273: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2610; 22)
+361317: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2611; 22)
+361426: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2612; 22)
+361492: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2613; 22)
+361571: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2614; 22)
Time used: 26501.6 secs.  Memory used: 351.6 Mb.
+361684: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2615; 22)
+361714: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2616; 22)
+361748: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2617; 22)
+361802: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2618; 22)
+361828: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2619; 22)
+361840: mip = 

+370475: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2712; 22)
+370604: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2713; 22)
+370810: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2714; 22)
+370943: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2715; 22)
+371072: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2716; 22)
+371222: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2717; 22)
Time used: 27398.9 secs.  Memory used: 351.9 Mb.
+371352: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2718; 22)
+371493: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2719; 22)
+371625: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2720; 22)
+371753: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2721; 22)
+371960: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2722; 22)
+372099: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2723; 22)
+372218: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2724; 22)
Time used: 2746

+383734: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2816; 22)
+383916: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2817; 22)
+384146: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2818; 22)
+384319: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2819; 22)
Time used: 28355.8 secs.  Memory used: 352.2 Mb.
+384525: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2820; 22)
+384688: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2821; 22)
+384995: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2822; 22)
+385184: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2823; 22)
+385299: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2824; 22)
+385547: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2825; 22)
Time used: 28418.5 secs.  Memory used: 352.3 Mb.
+385658: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2826; 22)
+385993: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2827; 22)
+386245: mip =   1.540000000e+02 >=   

+394510: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2919; 22)
+394539: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2920; 22)
+394607: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2921; 22)
+394701: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2921; 22)
+394720: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2922; 22)
+394787: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2923; 22)
+394904: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2924; 22)
+394975: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2925; 22)
Time used: 29382.8 secs.  Memory used: 352.5 Mb.
+395047: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2926; 22)
+395125: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2927; 22)
+395176: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2928; 22)
+395238: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2929; 22)
+395294: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (2930; 22)
+395376: mip = 

+400721: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3024; 22)
+400722: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3025; 22)
+400744: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3026; 22)
+400806: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3027; 22)
+400807: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3028; 22)
+400808: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3029; 22)
+400809: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3030; 22)
+400810: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3031; 22)
+400877: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3032; 22)
+400927: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3033; 22)
Time used: 30155.3 secs.  Memory used: 352.7 Mb.
+400970: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3034; 22)
+401015: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3035; 22)
+401048: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3036; 22)
+401049: mip = 

+405522: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3130; 22)
+405644: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3131; 22)
+405768: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3132; 22)
Time used: 30919.3 secs.  Memory used: 352.9 Mb.
+405830: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3133; 22)
+405852: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3134; 22)
+405991: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3135; 22)
+406118: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3136; 22)
+406189: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3137; 22)
+406255: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3138; 22)
+406391: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3139; 22)
+406479: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3140; 22)
Time used: 30981.9 secs.  Memory used: 352.9 Mb.
+406492: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3141; 22)
+406494: mip =   1.540000000e+02 >=   

+414092: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3235; 22)
+414239: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3236; 22)
+414342: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3237; 22)
+414405: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3238; 22)
+414466: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3239; 22)
+414492: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3240; 22)
+414568: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3241; 22)
+414647: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3242; 22)
Time used: 31744.7 secs.  Memory used: 353.1 Mb.
+414863: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3243; 22)
+414958: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3244; 22)
+415034: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3245; 22)
+415122: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3246; 22)
+415226: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3247; 22)
+415300: mip = 

+424108: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3339; 22)
+424177: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3340; 22)
Time used: 32589.8 secs.  Memory used: 353.4 Mb.
+424178: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3341; 22)
+424325: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3342; 22)
+424379: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3343; 22)
+424552: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3344; 22)
+424591: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3345; 22)
+424651: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3346; 22)
+424708: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3347; 22)
Time used: 32653.2 secs.  Memory used: 353.4 Mb.
+424849: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3348; 22)
+424923: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3349; 22)
+424934: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3350; 22)
+424956: mip =   1.540000000e+02 >=   

+433281: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3443; 22)
+433361: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3444; 22)
+433552: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3445; 22)
+433723: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3446; 22)
+433859: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3447; 22)
Time used: 33567.7 secs.  Memory used: 353.6 Mb.
+433954: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3448; 22)
+433962: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3449; 22)
+433963: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3450; 22)
+433964: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3451; 22)
+434103: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3452; 22)
+434201: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3453; 22)
+434343: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3454; 22)
Time used: 33631.9 secs.  Memory used: 353.6 Mb.
+434426: mip =   1.540000000e+02 >=   

+442220: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3548; 22)
Time used: 34460.1 secs.  Memory used: 353.9 Mb.
+442377: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3549; 22)
+442511: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3550; 22)
+442738: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3551; 22)
+442990: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3552; 22)
+443082: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3553; 22)
+443337: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3554; 22)
+443424: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3555; 22)
Time used: 34523.1 secs.  Memory used: 353.9 Mb.
+443590: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3556; 22)
+443816: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3557; 22)
+443905: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3558; 22)
+444080: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3559; 22)
+444270: mip =   1.540000000e+02 >=   

+455235: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3653; 22)
+455303: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3654; 22)
+455440: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3655; 22)
+455676: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3656; 22)
+455819: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3657; 22)
Time used: 35348.7 secs.  Memory used: 354.2 Mb.
+456020: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3658; 22)
+456193: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3659; 22)
+456355: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3660; 22)
+456494: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3661; 22)
+456703: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3662; 22)
+456882: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3663; 22)
+456997: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3664; 22)
+457218: mip =   1.540000000e+02 >=   1.600000000e+01  89.6% (3665; 22)
Time used: 3541

+461065: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3745; 204)
+461079: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3746; 204)
Time used: 36053.7 secs.  Memory used: 354.7 Mb.
+461123: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3747; 204)
+461242: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3748; 204)
+461272: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3749; 204)
+461324: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3750; 204)
+461404: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3751; 204)
+461464: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3752; 204)
+461483: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3753; 204)
Time used: 36120.6 secs.  Memory used: 354.7 Mb.
+461511: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3754; 204)
+461580: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3755; 204)
+461616: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3756; 204)
+461689: mip =   1.3800000

+465350: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3848; 204)
+465356: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3849; 204)
+465358: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3850; 204)
+465445: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3851; 204)
+465546: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3852; 204)
Time used: 37014.8 secs.  Memory used: 354.8 Mb.
+465578: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3853; 204)
+465669: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3854; 204)
+465807: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3855; 204)
+465917: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3856; 204)
+466123: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3857; 204)
+466235: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3858; 204)
+466299: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3859; 204)
Time used: 37078.3 secs.  Memory used: 354.8 Mb.
+466329: mip =   1.3800000

+473837: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3951; 204)
+473901: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3952; 204)
+474128: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3953; 204)
Time used: 37973.1 secs.  Memory used: 355.0 Mb.
+474236: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3954; 204)
+474419: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3955; 204)
+474542: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3956; 204)
+474761: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3957; 204)
+474827: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3958; 204)
+475035: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3959; 204)
Time used: 38034.1 secs.  Memory used: 355.1 Mb.
+475103: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3960; 204)
+475232: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3961; 204)
+475331: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (3962; 204)
+475548: mip =   1.3800000

+491360: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4053; 204)
+491511: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4054; 204)
+491768: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4055; 204)
+491806: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4056; 204)
+492019: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4057; 204)
+492196: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4058; 204)
Time used: 39041.0 secs.  Memory used: 355.5 Mb.
+492240: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4059; 204)
+492340: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4060; 204)
+492476: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4061; 204)
+492590: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4062; 204)
+492724: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4063; 204)
+492887: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4064; 204)
Time used: 39104.2 secs.  Memory used: 355.5 Mb.
+493110: mip =   1.3800000

+505097: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4156; 204)
Time used: 40008.7 secs.  Memory used: 355.8 Mb.
+505240: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4157; 204)
+505288: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4158; 204)
+505383: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4159; 204)
+505412: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4160; 204)
+505538: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4161; 204)
+505651: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4162; 204)
+505709: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4163; 204)
Time used: 40072.8 secs.  Memory used: 355.9 Mb.
+505858: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4164; 204)
+505892: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4165; 204)
+506077: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4166; 204)
+506142: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4167; 204)
+506330: mip =   1.3800000

+518271: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4259; 204)
+518272: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4260; 204)
+518273: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4261; 204)
+518274: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4262; 204)
+518275: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4263; 204)
+518276: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4264; 204)
+518277: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4265; 204)
+518278: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4266; 204)
+518279: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4267; 204)
Time used: 40957.1 secs.  Memory used: 356.2 Mb.
+518349: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4268; 204)
+518442: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4269; 204)
+518509: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4270; 204)
+518708: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4271; 204)
+5

+529002: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4363; 204)
+529274: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4364; 204)
+529538: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4365; 204)
Time used: 41809.1 secs.  Memory used: 356.5 Mb.
+529747: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4366; 204)
+529826: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4367; 204)
+529914: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4368; 204)
+530083: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4369; 204)
+530234: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4370; 204)
+530331: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4371; 204)
+530418: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4372; 204)
+530503: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4373; 204)
+530581: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4374; 204)
Time used: 41875.4 secs.  Memory used: 356.5 Mb.
+530680: mip =   1.3800000

+539666: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4466; 204)
+539803: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4467; 204)
+539953: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4468; 204)
+540068: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4469; 204)
+540155: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4470; 204)
Time used: 42700.8 secs.  Memory used: 356.8 Mb.
+540355: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4471; 204)
+540431: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4472; 204)
+540566: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4473; 204)
+540718: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4474; 204)
+540909: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4475; 204)
+541013: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4476; 204)
+541021: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4477; 204)
Time used: 42763.9 secs.  Memory used: 356.8 Mb.
+541210: mip =   1.3800000

+557069: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4569; 204)
+557070: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4570; 204)
+557084: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4571; 204)
+557085: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4572; 204)
+557086: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4573; 204)
Time used: 43584.7 secs.  Memory used: 357.2 Mb.
+557091: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4574; 204)
+557105: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4575; 204)
+557106: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4576; 204)
+557112: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4577; 204)
+557118: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4578; 204)
+557119: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4579; 204)
+557123: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4580; 204)
+557130: mip =   1.380000000e+02 >=   1.700000000e+01  87.7% (4581; 204)
Ti

+564879: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4696; 256)
+564945: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4697; 256)
+565040: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4698; 256)
+565041: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4699; 256)
+565042: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4700; 256)
+565043: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4701; 256)
+565044: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4702; 256)
Time used: 44334.7 secs.  Memory used: 357.6 Mb.
+565045: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4703; 256)
+565109: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4704; 256)
+565167: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4705; 256)
+565256: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4706; 256)
+565330: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4707; 256)
+565354: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4708; 256)
+5

+574141: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4799; 256)
+574230: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4800; 256)
+574293: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4801; 256)
+574429: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4802; 256)
+574504: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4803; 256)
Time used: 45242.0 secs.  Memory used: 357.8 Mb.
+574637: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4804; 256)
+574799: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4805; 256)
+575030: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4806; 256)
+575199: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4807; 256)
+575323: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4808; 256)
+575520: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4809; 256)
+575563: mip =   1.340000000e+02 >=   1.700000000e+01  87.3% (4810; 256)
Time used: 45309.4 secs.  Memory used: 357.9 Mb.
+575814: mip =   1.3400000

+588078: >>>>>   1.170000000e+02 >=   1.700000000e+01  85.5% (4917; 256)
+590110: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4698; 538)
+590359: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4699; 538)
+590360: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4700; 538)
+590361: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4701; 538)
+590362: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4702; 538)
+590363: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4703; 538)
Time used: 46211.3 secs.  Memory used: 358.6 Mb.
+590364: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4704; 538)
+590365: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4705; 538)
+590366: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4706; 538)
+590367: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4707; 538)
+590368: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4708; 538)
+590661: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4709; 538)
+5

+597885: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4799; 538)
+597963: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4800; 538)
+598095: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4801; 538)
+598226: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4802; 538)
+598350: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4803; 538)
Time used: 47239.2 secs.  Memory used: 358.6 Mb.
+598418: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4804; 538)
+598482: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4805; 538)
+598487: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4806; 538)
+598539: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4807; 538)
+598540: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4808; 538)
+598541: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4809; 538)
Time used: 47300.9 secs.  Memory used: 358.6 Mb.
+598542: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4810; 538)
+598543: mip =   1.1700000

+607196: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4900; 538)
+607197: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4901; 538)
+607198: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4902; 538)
+607199: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4903; 538)
+607200: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4904; 538)
Time used: 48326.3 secs.  Memory used: 358.9 Mb.
+607201: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4905; 538)
+607287: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4906; 538)
+607352: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4907; 538)
+607447: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4908; 538)
+607531: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4909; 538)
+607663: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4910; 538)
Time used: 48389.3 secs.  Memory used: 358.9 Mb.
+607799: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (4911; 538)
+607905: mip =   1.1700000

+620488: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5002; 538)
+620549: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5003; 538)
+620654: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5004; 538)
+620655: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5005; 538)
+620656: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5006; 538)
+620741: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5007; 538)
Time used: 49405.1 secs.  Memory used: 359.4 Mb.
+620895: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5008; 538)
+620940: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5009; 538)
+620941: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5010; 538)
+621111: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5011; 538)
+621355: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5012; 538)
+621581: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5013; 538)
Time used: 49475.8 secs.  Memory used: 359.4 Mb.
+621856: mip =   1.1700000

+632040: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5104; 538)
+632144: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5105; 538)
+632232: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5106; 538)
+632323: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5107; 538)
+632401: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5108; 538)
+632496: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5109; 538)
Time used: 50452.5 secs.  Memory used: 359.7 Mb.
+632626: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5110; 538)
+632752: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5111; 538)
+632805: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5112; 538)
+632957: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5113; 538)
+633104: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5114; 538)
+633183: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5115; 538)
+633226: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5116; 538)
Ti

+646115: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5207; 538)
+646344: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5208; 538)
+646574: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5209; 538)
Time used: 51425.3 secs.  Memory used: 360.1 Mb.
+646799: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5210; 538)
+646939: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5211; 538)
+647047: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5212; 538)
+647168: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5213; 538)
+647318: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5214; 538)
+647412: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5215; 538)
Time used: 51487.6 secs.  Memory used: 360.1 Mb.
+647472: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5216; 538)
+647628: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5217; 538)
+647794: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5218; 538)
+647945: mip =   1.1700000

+664517: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5309; 538)
+664742: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5310; 538)
Time used: 52466.1 secs.  Memory used: 360.5 Mb.
+665058: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5311; 538)
+665122: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5312; 538)
+665240: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5313; 538)
+665447: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5314; 538)
+665587: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5315; 538)
+665694: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5316; 538)
+665769: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5317; 538)
Time used: 52529.6 secs.  Memory used: 360.6 Mb.
+665851: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5318; 538)
+666036: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5319; 538)
+666129: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5320; 538)
+666342: mip =   1.1700000

+677950: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5412; 538)
+678316: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5413; 538)
+678628: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5414; 538)
+678718: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5415; 538)
+678817: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5416; 538)
+678877: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5417; 538)
+678955: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5418; 538)
+679550: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5419; 538)
Time used: 53427.6 secs.  Memory used: 360.9 Mb.
+679895: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5420; 538)
+680047: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5421; 538)
+680216: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5422; 538)
+680434: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5423; 538)
+680641: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5424; 538)
+6

+689225: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5516; 538)
+689378: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5517; 538)
+689513: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5518; 538)
+689701: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5519; 538)
+689802: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5520; 538)
Time used: 54275.6 secs.  Memory used: 361.2 Mb.
+689962: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5521; 538)
+690099: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5522; 538)
+690197: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5523; 538)
+690408: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5524; 538)
+690454: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5525; 538)
+690587: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5526; 538)
+690739: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5527; 538)
+690921: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5528; 538)
Ti

+703773: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5619; 538)
+703774: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5620; 538)
+703775: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5621; 538)
Time used: 55160.4 secs.  Memory used: 361.6 Mb.
+703776: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5622; 538)
+703777: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5623; 538)
+703778: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5624; 538)
+703779: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5625; 538)
+703780: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5626; 538)
+703781: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5627; 538)
+703782: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5628; 538)
+703949: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5629; 538)
Time used: 55227.0 secs.  Memory used: 361.6 Mb.
+704136: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5630; 538)
+704325: mip =   1.1700000

+718091: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5723; 538)
+718189: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5724; 538)
Time used: 55998.1 secs.  Memory used: 361.9 Mb.
+718359: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5725; 538)
+718591: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5726; 538)
+718849: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5727; 538)
+719006: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5728; 538)
+719193: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5729; 538)
+719368: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5730; 538)
+719588: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5731; 538)
Time used: 56059.2 secs.  Memory used: 361.9 Mb.
+719785: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5732; 538)
+719937: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5733; 538)
+720109: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5734; 538)
+720438: mip =   1.1700000

+734324: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5828; 538)
+734486: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5829; 538)
+734904: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5830; 538)
+735221: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5831; 538)
+735302: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5832; 538)
+735350: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5833; 538)
+735460: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5834; 538)
+735472: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5835; 538)
+735542: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5836; 538)
+735599: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5837; 538)
+735759: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5838; 538)
Time used: 56831.2 secs.  Memory used: 362.3 Mb.
+735926: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5839; 538)
+736092: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5840; 538)
+7

+748915: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5932; 538)
+749100: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5933; 538)
+749319: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5934; 538)
+749520: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5935; 538)
+749678: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5936; 538)
Time used: 57522.3 secs.  Memory used: 362.7 Mb.
+749874: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5937; 538)
+749985: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5938; 538)
+750088: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5939; 538)
+750219: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5940; 538)
+750310: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5941; 538)
+750439: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5942; 538)
+750532: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5943; 538)
+750622: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (5944; 538)
+7

+760396: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6045; 538)
Time used: 58148.7 secs.  Memory used: 362.9 Mb.
+760470: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6046; 538)
+760610: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6048; 538)
+760714: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6050; 538)
+760729: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6051; 538)
+761100: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6053; 538)
+761317: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6054; 538)
+761469: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6056; 538)
Time used: 58211.9 secs.  Memory used: 363.0 Mb.
+761520: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6058; 538)
+761633: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6059; 538)
+761785: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6060; 538)
+761827: mip =   1.170000000e+02 >=   1.700000000e+01  85.5% (6061; 538)
+762065: mip =   1.1700000

+768199: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6147; 548)
+768248: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6148; 548)
+768342: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6149; 548)
+768372: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6150; 548)
Time used: 59065.8 secs.  Memory used: 363.3 Mb.
+768486: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6151; 548)
+768551: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6152; 548)
+768748: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6153; 548)
+768866: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6154; 548)
+768975: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6155; 548)
+769234: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6156; 548)
Time used: 59128.8 secs.  Memory used: 363.3 Mb.
+769350: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6157; 548)
+769351: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6158; 548)
+769352: mip =   1.1600000

+778385: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6248; 548)
+778476: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6249; 548)
+778650: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6250; 548)
+778804: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6251; 548)
+778957: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6252; 548)
Time used: 60185.7 secs.  Memory used: 363.6 Mb.
+779133: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6253; 548)
+779244: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6254; 548)
+779371: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6255; 548)
+779499: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6256; 548)
+779678: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6257; 548)
+779809: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6258; 548)
Time used: 60254.7 secs.  Memory used: 363.7 Mb.
+780033: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6259; 548)
+780207: mip =   1.1600000

+794690: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6350; 548)
+794841: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6351; 548)
+795035: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6352; 548)
+795290: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6353; 548)
+795498: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6354; 548)
+795595: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6355; 548)
Time used: 61212.9 secs.  Memory used: 364.1 Mb.
+795812: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6356; 548)
+796019: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6357; 548)
+796181: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6358; 548)
+796312: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6359; 548)
+796428: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6360; 548)
+796600: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6361; 548)
+796669: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6362; 548)
Ti

+808261: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6453; 548)
+808531: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6454; 548)
+808843: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6455; 548)
Time used: 62199.9 secs.  Memory used: 364.4 Mb.
+809134: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6456; 548)
+809393: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6457; 548)
+809684: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6458; 548)
+809801: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6459; 548)
+810076: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6460; 548)
+810212: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6461; 548)
+810381: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6462; 548)
Time used: 62268.0 secs.  Memory used: 364.5 Mb.
+810503: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6463; 548)
+810728: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6464; 548)
+810811: mip =   1.1600000

+822015: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6556; 548)
+822027: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6557; 548)
+822028: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6558; 548)
+822029: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6559; 548)
+822030: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6560; 548)
+822031: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6561; 548)
Time used: 63251.3 secs.  Memory used: 364.8 Mb.
+822032: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6562; 548)
+822033: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6563; 548)
+822183: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6564; 548)
+822293: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6565; 548)
+822406: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6566; 548)
+822451: mip =   1.160000000e+02 >=   1.700000000e+01  85.3% (6567; 548)
Time used: 63315.3 secs.  Memory used: 364.8 Mb.
+822592: mip =   1.1600000

In [52]:
instance.Cmax.get_values()

{None: 62.0}

In [53]:
for k,v in instance.X.get_values().items():
    if v == 1:
        print(k,v)

(0, 0, 2) 1.0
(0, 1, 29) 1.0
(0, 2, 11) 1.0
(0, 2, 20) 1.0
(0, 5, 42) 1.0
(1, 0, 19) 1.0
(1, 3, 0) 1.0
(1, 4, 28) 1.0
(1, 8, 37) 1.0
(1, 12, 10) 1.0
(2, 9, 1) 1.0
(2, 10, 21) 1.0
(2, 11, 30) 1.0
(2, 13, 12) 1.0
(3, 6, 32) 1.0
(3, 7, 2) 1.0
(3, 14, 19) 1.0


In [37]:
D = np.zeros((50, 4, 15))
for k,v in instance.X.get_values().items():
    if v == 1:
        D[k[2],k[0],k[1]] = 1
for t in range(D.shape[0]):
    if D[t,:,:].sum() > 0:
        print(t, D[t,:,:])

0 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
4 [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
7 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
8 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
13 [[0. 0. 0. 0. 1. 0. 0.

[23, 14, 7, 62, 21, 17, 19, 55, 16, 13, 27, 31, 35, 18, 9]